### ISSUE TITLE
use use_modular_headers!

### ISSUE THREAD

**Issue by myeveryheart** [pmusolino/PMAlertController#68]
For some reason, I am not using use_frameworks!, but use_modular_headers! instead.
Then it comes with error:
```
Unable to run command 'StripNIB PMAlertController.nib' - this target might include its own product.
Unable to run command 'StripNIB PMAlertController~iphone.nib' - this target might include its own product.
Unable to run command 'StripNIB PMAlertController~ipad.nib' - this target might include its own product.
```

**Comment by pmusolino** [comment]
Can you try using `pod 'PMAlertController', :modular_headers => false,`?

**Comment by myeveryheart** [comment]
Yes, I tried, but it didn't work.

**Comment by VincentSit** [comment]
Static libraries are completely different from dynamic frameworks, it is not a container or bundle.

A static library is a single file that contains classes, code and variables that were linked together by the library creator. It does not "contain" other files, it is essentially a database of compiled code. 

Based on the above explanation, you can not use PMAlertController as a static library since you can not package xib file into static library.

`use_modular_headers!` is needed only if your Swift pod depends on an Objective-C pod. Detailed [here](http://blog.cocoapods.org/CocoaPods-1.5.0/). It doesn't make sense to use it here.

CocoaPods currently does not support mixing static libraries and dynamic frameworks in a project, and from their Issue, there is little likelihood of future support.

So I suggest you keep other pods as static libraries and package PMAlertController into a dynamic framework separately, used as an embedded framework. To do this, [Carthage](https://github.com/Carthage/Carthage) can help you.

**Comment by pmusolino** [comment]
Thanks @VincentSit for clarifying this aspect.
